import { NextRequest, NextResponse } from 'next/server'
import { generateConfig } from '@/lib/generator'
import JSZip from 'jszip'

export async function POST(request: NextRequest) {
  const body = await request.json()
  const { metier, nom, answers, langue = 'fr' } = body

  if (!metier || !nom || !answers) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  try {
    const config = await generateConfig({ metier, nom, answers, langue })

    // Créer le ZIP
    const zip = new JSZip()
    const folder = zip.folder('openclaw-config')!

    folder.file('SOUL.md', config.soul || '')
    folder.file('IDENTITY.md', config.identity || '')
    folder.file('USER.md', config.user || '')
    folder.file('HEARTBEAT.md', config.heartbeat || '')
    folder.file('TOOLS.md', config.tools || '')
    folder.file('GUIDE.md', config.guide || '')
    folder.file('README.txt', `OpenClaw Configuration for ${nom} — ${metier}
Generated by ClawConfig
================================

FILES INCLUDED:
- SOUL.md      → Copy to ~/.openclaw/workspace/
- IDENTITY.md  → Copy to ~/.openclaw/workspace/
- USER.md      → Copy to ~/.openclaw/workspace/
- HEARTBEAT.md → Copy to ~/.openclaw/workspace/
- TOOLS.md     → Copy to ~/.openclaw/workspace/
- GUIDE.md     → Read this first!

INSTALL:
1. Read GUIDE.md
2. Copy all .md files to your OpenClaw workspace
3. Restart OpenClaw
4. Your AI is ready for: ${metier}

Support: https://openclaw.ai
`)

    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' })

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="openclaw-${metier.toLowerCase().replace(/\s+/g, '-')}.zip"`,
      }
    })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: 'Generation failed' }, { status: 500 })
  }
}
