import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { generateConfig } from '@/lib/generator'
import { METIERS } from '@/lib/metiers'
import JSZip from 'jszip'

const ALLOWED_METIERS = METIERS.map((m) => m.nom) as [string, ...string[]]

const answerValue = z.union([
  z.string().max(2000),
  z.array(z.string().max(500)).max(50),
])

const BodySchema = z.object({
  metier: z.enum(ALLOWED_METIERS),
  nom: z.string().trim().min(1).max(80),
  langue: z.enum(['fr', 'en']).default('fr'),
  answers: z.record(z.string().max(80), answerValue),
})

export async function POST(request: NextRequest) {
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const parsed = BodySchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: 'Invalid input', issues: parsed.error.flatten() },
      { status: 400 },
    )
  }

  const { metier, nom, answers, langue } = parsed.data

  try {
    const config = await generateConfig({ metier, nom, answers, langue })

    const zip = new JSZip()
    const folder = zip.folder('openclaw-config')!

    folder.file('SOUL.md', config.soul || '')
    folder.file('IDENTITY.md', config.identity || '')
    folder.file('USER.md', config.user || '')
    folder.file('HEARTBEAT.md', config.heartbeat || '')
    folder.file('TOOLS.md', config.tools || '')
    folder.file('GUIDE.md', config.guide || '')
    folder.file(
      'README.txt',
      `OpenClaw Configuration for ${nom} — ${metier}
Generated by ClawConfig
================================

FILES INCLUDED:
- SOUL.md      → Copy to ~/.openclaw/workspace/
- IDENTITY.md  → Copy to ~/.openclaw/workspace/
- USER.md      → Copy to ~/.openclaw/workspace/
- HEARTBEAT.md → Copy to ~/.openclaw/workspace/
- TOOLS.md     → Copy to ~/.openclaw/workspace/
- GUIDE.md     → Read this first!

INSTALL:
1. Read GUIDE.md
2. Copy all .md files to your OpenClaw workspace
3. Restart OpenClaw
4. Your AI is ready for: ${metier}

Support: https://openclaw.ai
`,
    )

    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' })
    const uint8 = new Uint8Array(zipBuffer)

    const safeName = metier.toLowerCase().replace(/[^a-z0-9]+/g, '-')

    return new NextResponse(uint8, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="openclaw-${safeName}.zip"`,
      },
    })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: 'Generation failed' }, { status: 500 })
  }
}
